site_name: ИТМО 5 Web-программирование
nav:
  - Главная: index.md
  - ЛР №1:
    - Задача_1: lab_1/task_1.md
    - Задача_2: lab_1/task_2.md
    - Задача_3: lab_1/task_3.md
    - Задача_4: lab_1/task_4.md
    - Задача_5: lab_1/task_5.md
    - Вывод: lab_1/conclusion.md
  - ЛР №2:
    - Задача_1: lab_2/task_1.md
  - ЛР №3:
    - Задача_1: lab_3/lab.md
  - ЛР №4:
    - Задача_1: lab_4/lab.md
  - Практики:
    - Практика 3.1: practice_31/practice_3_1.md
    - Практика 3.2: practice_32/practice_3_2.md
